baseurl = "/"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "Familink"
theme = "hugo-universal-theme"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Your name"
	description = "Describe your website"

	style = "green"
	email = "alexis@asweshare.com"
	about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."
    logo = "img/banner2.png"
    address = """<p><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """


	[params.topbar]
	    enable = true
	    text = "Familink"


	[params.carousel]
	    enable = true
	    # All carousel items are defined in their own files. You can find example items
	    # at 'exampleSite/data/carousel'.
	    # For more informtion take a look at the README.

	[params.features]
	    enable = true
	    # All features are defined in their own files. You can find example items
	    # at 'exampleSite/data/features'.
	    # For more informtion take a look at the README.

	[params.testimonials]
	    enable = true
	    # All testimonials are defined in their own files. You can find example items
	    # at 'exampleSite/data/testimonials'.
	    # For more informtion take a look at the README.
	    title = "Testimonials"
	    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 4

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:your@email.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"