baseurl = "/"
defaultContentLanguage = "fr"
googleAnalytics = ""
languageCode = "fr-FR"
paginate = 10
theme = "hugo-universal-theme"
title = "Familink"
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4
[[menu.main]]
identifier = "faq"
name = "FAQ"
url = "/faq/"
weight = 3
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.topbar]]
name = "Email"
pre = "<i class='fa fa-2x fa-envelope'></i>"
url = "mailto:your@email.com"
weight = 4
[[menu.topbar]]
name = "Twitter"
pre = "<i class='fa fa-2x fa-twitter'></i>"
url = "http://twitter.com"
weight = 3
[[menu.topbar]]
name = "Facebook"
pre = "<i class='fa fa-2x fa-facebook'></i>"
url = "http://facebook.com"
weight = 2
[[menu.topbar]]
name = "GitHub"
pre = "<i class='fa fa-2x fa-github'></i>"
url = "https://github.com/devcows/hugo-universal-theme"
weight = 1
[params]
about_us = "<p>Familink est une marque de AsWeShare</p>"
address = "<p><strong>369 Sente Sainte Venise</strong>\n        <br>76230 Bois Guillaume\n        <br>\n        <strong>FRANCE</strong>\n      </p>\n      "
copyright = "Copyright (c) 2018."
description = "Describe your website"
email = "alexis@asweshare.com"
logo = "img/banner2.png"
name = "Your name"
style = "green"
[params.carousel]
enable = true
[params.familink_description]
enable = false
[params.features]
enable = true
[params.testimonials]
enable = true
subtitle = ""
title = "Témoignages"
[params.topbar]
enable = true
text = "Familink"
