---
baseurl: "/"
defaultContentLanguage: fr
googleAnalytics: ''
languageCode: fr-FR
paginate: 10
theme: hugo-universal-theme
title: Familink
menu:
  topbar:
  - name: Facebook
    pre: "<i class='fa fa-2x fa-facebook'></i>"
    url: https://facebook.com/familinkframe
    weight: 2
  - name: Twitter
    pre: "<i class='fa fa-2x fa-twitter'></i>"
    url: https://twitter.com/familinkframe
    weight: 3
  - name: Email
    pre: "<i class='fa fa-2x fa-envelope'></i>"
    url: mailto:contact@familinkframe.com
    weight: 4
params:
  about_us: "<p>Familink est une marque de AsWeShare</p>"
  address: |-
    <p><strong>369 Sente Sainte Venise</strong>
            <br>76230 Bois Guillaume
            <br>
            <strong>FRANCE</strong>
          </p>
  carousel:
    enable: true
  copyright: Copyright 2018.
  date_format: "2006-01-02"
  defaultdescription: Donner une utilité sociale à la technologie. Familink est un
    cadre photo connecté 3G dédié aux personnes âgées. Avec Familink les enfants peuvent
    envoyer des photos instantanément à leurs parents et grands-parents.
  defaultimage: "/img/opengraph_image.jpg"
  description: Describe your website
  email: contact@familinkframe.com
  familink_description:
    enable: true
  features:
    enable: true
  logo: img/banner2.png
  name: Your name
  recent_posts:
    enable: true
    subtitle: ''
    title: Actualités
  siren: 821282621
  style: turquoise
  testimonials:
    enable: true
    subtitle: ''
    title: Témoignages
  topbar:
    enable: true
    text: Familink
  tribunal: Rouen
  tva: FR54821282621
languages:
  en:
    weight: 1
    copyright: Copyright (c) 2018.
    languageName: English
    menu:
      main:
      - !ruby/hash:InsensitiveHash
        name: Contact
        url: "/en/contact/"
        weight: 4
      - !ruby/hash:InsensitiveHash
        identifier: faq
        name: FAQ
        url: "/en/faq/"
        weight: 3
      - !ruby/hash:InsensitiveHash
        name: Send pictures to my frames
        url: https://web.familinkframe.com/en
        weight: 2
      - !ruby/hash:InsensitiveHash
        name: Home
        url: "/"
        weight: 1
      topbar:
      - !ruby/hash:InsensitiveHash
        name: Facebook
        pre: "<i class='fa fa-2x fa-facebook'></i>"
        url: https://facebook.com/familinkframe
        weight: 2
      - !ruby/hash:InsensitiveHash
        name: Twitter
        pre: "<i class='fa fa-2x fa-twitter'></i>"
        url: https://twitter.com/familinkframe
        weight: 3
      - !ruby/hash:InsensitiveHash
        name: Email
        pre: "<i class='fa fa-2x fa-envelope'></i>"
        url: mailto:contact@familinkframe.com
        weight: 4
    params:
      recent_posts:
        enable: true
        title: Latest Posts
        subtitle: ''
      testimonials:
        enable: true
        subtitle: ''
        title: Testimonials
  fr:
    weight: 2
    languageName: Français
    menu:
      main:
      - !ruby/hash:InsensitiveHash
        identifier: faq
        name: FAQ
        url: "/faq/"
        weight: 6
      - !ruby/hash:InsensitiveHash
        identifier: tarifs
        name: Tarifs
        url: "/nos-tarifs/"
        weight: 5
      - !ruby/hash:InsensitiveHash
        name: Mes Cadres
        url: https://web.familinkframe.com/fr
        weight: 4
      - !ruby/hash:InsensitiveHash
        name: Contact
        url: "/contact/"
        weight: 3
      - !ruby/hash:InsensitiveHash
        name: Où Acheter
        url: "/ou-acheter"
        weight: 2
      - !ruby/hash:InsensitiveHash
        name: Boutique
        url: "/shop"
        weight: 1
      topbar:
      - !ruby/hash:InsensitiveHash
        name: Facebook
        pre: "<i class='fa fa-2x fa-facebook'></i>"
        url: https://facebook.com/familinkframe
        weight: 2
      - !ruby/hash:InsensitiveHash
        name: Twitter
        pre: "<i class='fa fa-2x fa-twitter'></i>"
        url: https://twitter.com/familinkframe
        weight: 3
      - !ruby/hash:InsensitiveHash
        name: Email
        pre: "<i class='fa fa-2x fa-envelope'></i>"
        url: mailto:contact@familinkframe.com
        weight: 4
  de:
    weight: 3
    copyright: Copyright (c) 2018.
    languageName: Deutsch
    menu:
      main:
      - !ruby/hash:InsensitiveHash
        identifier: faq
        name: FAQ
        url: "/de/faq/"
        weight: 6
      - !ruby/hash:InsensitiveHash
        identifier: tarifs
        name: Unsere Preise
        url: "/de/unsere-preise/"
        weight: 5
      - !ruby/hash:InsensitiveHash
        name: Bilder schicken
        url: https://web.familinkframe.com/en
        weight: 4
      - !ruby/hash:InsensitiveHash
        name: kontakt
        url: "/de/kontakt/"
        weight: 3
      - !ruby/hash:InsensitiveHash
        name: Kaufen
        url: "/de/shop"
        weight: 1
      topbar:
      - !ruby/hash:InsensitiveHash
        name: Facebook
        pre: "<i class='fa fa-2x fa-facebook'></i>"
        url: https://facebook.com/familink.de/
        weight: 2
      - !ruby/hash:InsensitiveHash
        name: Twitter
        pre: "<i class='fa fa-2x fa-twitter'></i>"
        url: https://twitter.com/familinkde
        weight: 3
      - !ruby/hash:InsensitiveHash
        name: Email
        pre: "<i class='fa fa-2x fa-envelope'></i>"
        url: mailto:contact@familink.de
        weight: 4
    params:
      defaultdescription: Der Familink Bilderrahmen wurde für Senioren entwickelt,
        die keine Internetverbindung zu Hause haben. Er funktioniert mit einer integrierten
        3G Sim Karte, die sich automatisch mit Internet verbindet. So können Enkelkinder
        Ihren Großeltern ganz einfach Bilder schicken!
      email: contact@familink.de
      about_us: "<p>Familink ist eine Marke von AsWeShare</p>"
      address: |-
        <p><strong>AsWeShare</strong>
                <br>369 Sente Sainte Venise
                <br>76230 Bois Guillaume
                <br>
                <strong>FRANKREICH</strong>
              </p>
      recent_posts:
        enable: true
        title: Nachrichten
        subtitle: ''
      testimonials:
        enable: true
        subtitle: ''
        title: Erfahrungsberichte
